### PR TITLE
Widget Updates!

### PR DESCRIPTION
**Pull request by xbakesx**
Hey Jay.

So I noticed that most of the reviews were complaining that the widget doesn't update.  It does technically update, but you have to wait for it to do that which happens every half hour or something silly.  So now whenever the cache gets updated (via the end of a phone call, or via the app) the widgets all get updated, yay!

In other news, I moved the "minutes remaining" toast up to the top, so that it doesn't cover anything up, and now that it's not covering anything up, I made it toast long, instead of toast short.  

I also added "Virgin Mobile Minutes Checker:" to the toast, so that people know where that came from.

I plan on adding in a settings screen so that you can decide if you want the toasts, and whether or not the toast should show the app name... but I figured I should ask you how you feel about adding settings (that makes it seem like a much bigger app for some reason).

### CODE REVIEW

**Comment by poundifdef** [comment]
Hi! This is really good, I'll look at this over today and tomorrow and do an update this week (rather than after 6 months. promise!)

I'd love to see a "Preferences" screen to turn the toast on and off. In fact, drfloob had written a preferences screen that did just that, which we are not currently using, so I was planning on re-integrating that with your service code. (He himself wasn't keen on doing all of that merging. So if you want to do so, then great, otherwise I will.)

One quick question before I merge this: after a call ends, do you wait a few seconds before attempting to retrieve the newest minutes count? (If you don't, then the call will fail sporadically because all of the "phone call" processes haven't been cleaned up yet; you can see some discussion of this in the commit logs).

The "preferences" screen should be a separate pull request than this, so don't close this one!

Cheers, 

Jay

**Comment by poundifdef** [comment]
Also - lest our branches get too far apart - you might want to go ahead and merge in my (minor) changes from the production release to your repo?

**Comment by xbakesx** [comment]
First, I already have a settings screen implemented and working just not
committed :-) so I can commit that.  It's not super pretty, but what
settings screen is?

I wait 10 seconds after the call, because I was seeing the same behavior.

To grab your changes and do the merge, what do I do on github?  Can you
issue a pull request to me, and I can pull your code into mine?  I don't
seem to be able to do that... but I assume you can logged in as you?
~Alex

On Jul 3, 2011 2:46 PM, "poundifdef" <
reply@reply.github.com>
wrote:

**Comment by xbakesx** [comment]
Alright, I updated the preferences a little, and merged your changes, and updated the version.  You may want to double check the version so that I was following the same pattern you were before, I just incremented both numbers : )

Check it out, but this should be good to go.

PS I was thinking about putting a preference in for "use the old interface" so if people really liked the super simple interface, they could... thoughts?

**Comment by poundifdef** [comment]
There is actually an android.preference.PreferenceManager class which basically takes care of all preference-related code! drfloob's preference screen looked really good, so I'm going to merge his Intent with your service code. 

I just committed a small change which adds the preferences screen: https://github.com/poundifdef/VirginMobileMinutesChecker/commit/df8b43e6b8e7e6e2154180a556c2bf90bf129691

That change was part of a previous pull request from drfloob: https://github.com/drfloob/VirginMobileMinutesChecker/commit/9183777d368d25ce844cf46347d8d68ae1137071

If you run the app that is in my current branch, you can look at his prefs screen (and code). Now it has to be made /functional/.

I think the only new preference (in addition to the "pre/post call toast") is one that says "Show Pie Graph On Minutes Screen". That way the user can remove that graphic if it's distracting. besides that, I see no need to revert to the old pre-multiple-accounts intent. In the future I'd like to remove that old code altogether.

In that respect - and of course I have no idea how to do this in git - can you roll your pull request back to before adding the preferences screen? That way I can do smaller merges of code (instead of adding tons of features at once!)

**Comment by poundifdef** [comment]
That is, I think I will merge from this commit as a start: https://github.com/xbakesx/VirginMobileMinutesChecker/commit/6e8e8ed04ac778b8501f266596efa440ecfef175

**Comment by xbakesx** [comment]
I merged the changes, using the built-in preferences and pushed everything up to my branch : )

**Pull request merged**
