### PR TITLE
Widget

### PR DESCRIPTION
**Pull request by xbakesx**
Hey Jay,

Sorry this seems to be pretty inopportune given I just told you I wasn't going to get around to it and you told me you were going to merge in someone else's widget.

At the very least you can pull this in and remove my widget from the Manifest.  

It's a really simple 2x1 widget that prints out your balance and minutes used as well as the time we updated your minutes.  We only update your minutes on phone calls and when you single tap the widget.  

I am still working on a nice pie chart so that we can have a 1x1 widget and more information at a glance.  

Good luck,
Alex

### CODE REVIEW

**Comment by poundifdef** [comment]
Hey - no worries on writing your own widget; ultimately the goal is to push out new features for the users!

I am unfortunately having trouble building; both widget.xml and widget_2x1.xml both define an element called "widget_background":

```
jpgoel@coltrane:$ ant compile
Buildfile: build.xml
    [setup] Android SDK Tools Revision 8
    [setup] Project Target: Android 2.1-update1
    [setup] API level: 7
    [setup] 
    [setup] ------------------
    [setup] Resolving library dependencies:
    [setup] No library dependencies.
    [setup] 
    [setup] ------------------
    [setup] 
    [setup] 
    [setup] Importing rules file: tools/ant/main_rules.xml

-dirs:
     [echo] Creating output directories if needed...

-pre-build:

-resource-src:
     [echo] Generating R.java / Manifest.java from the resources...
     [null] res/drawable/widget_background.xml:0: error: Resource entry widget_background is already defined.
     [null] res/drawable/widget_background.png:0: Originally defined here.

BUILD FAILED
```

Could you help clarify this please (or maybe checkin a fix?)

Thanks so much for working on this!

Jay

**Comment by xbakesx** [comment]
Hmm...

I can't get anything to compile from the command line with build.xml I get a
weird problem:
BUILD FAILED
C:\Documents and
Settings\us693090\git\vm\VirginMobileMinutesChecker\build.xml:5
1: taskdef class com.android.ant.SetupTask cannot be found
 using the classloader AntClassLoader[]

I just updated my repository and moved my widget_background so hopefully
that fixes things?  If it doesn't I will dig further into why I can't get
the xml to build... but regardless I won't be seeing the same problem you're
seeing because I don't have the changes you pulled in from somewhere else
:-/  Do I have to pull in changes from your repository?  I suppose I do that
through github somewhere...

~Alex

**Comment by poundifdef** [comment]
Hi! If you could make two small changes, I will accept this pull request.
1. Could you merge in my latest version of com.jaygoel.virginminuteschecker.WebsiteScraper.java? This has the code pertaining to VM's latest website update, along with some StringBuilder stuff.
2. In res/drawable/, if you delete either `android_widget.png` or `android_widget.xml`, it will compile just fine. I don't quite know which one is supposed to be there, but when I try to `ant compile` with both of them, then it doesn't work :(

Thanks so much!

**Comment by poundifdef** [comment]
Can you issue a new pull request, with your latest code?

**Pull request closed without merging**
