### PR TITLE
OnCall Minutes Notifier

### PR DESCRIPTION
**Pull request by drfloob**
I've made some minor changes to your original code, and I added the one feature I really wanted. To try and sum up:

There's a background service and broadcastreceiver combo that listen for phone call events and display the minutes remaining in a small toast notification. This can be turned on and off in the new settings menu, which differentiates between incoming and outgoing calls (kind of). Since parsing/scraping can take some time, the minutes displayed are actually from a cache. Every time a call ends, or when someone starts the gui, the cache is updated from a fresh scrape (which _seems_ to be updated in realtime ... good on Virgin Mobile). The notification fails semi-gracefully if the user is "logged out", showing "Minutes Used: Unknown" and prompting the user for login credentials when the call is finished (if the service is turned on in the prefs).

Pretty sweet, huh?

### CODE REVIEW

**Comment by drfloob** [comment]
Disregard this pull request, I'm going to submit another. It turns out I left in one import statement for a deleted class, and it wouldn't compile.

**Comment by drfloob** [comment]
I don't know how to use pull requests :). It looks like my changes from this morning are included in this pull request (that I created yesterday), oddly enough.

**Comment by poundifdef** [comment]
I created a new branch called "dev_contrib" so that I could rummage around your changes before folding them into "master". I, of course, have no idea how to use pull requests (or git for that matter) so I hope I have done so correctly. At first glance all of this looks extremely nifty - a much-needed refactor and code cleanup too. Curious - may I fold the code in `com.drfloob.*` into `com.jaygoel.*` ? Or is your preference that it have its own package name for the next person to see? I will certainly add a "credits" screen before updating the app on the market - I'm happy to give you credit/link juice for your work.

**Comment by drfloob** [comment]
I'd prefer to keep the classes I wrote in com.drfloob.\* . I wrote new general classes in the com.jaygoel.\* package (see Preferences and the various Scraper classes). Do you anticipate that using different package names would cause any problems?

**Comment by poundifdef** [comment]
My apologies for not updating the app yet! I'm working on just a few tweaks: adding more to the unit tests, figuring out why your ant script won't work when I try to test on my phone (I think this is a signature issue), and figuring out why eclipse (which is better than emacs admittedly but worse than vim :P) won't parse your ant script.

I am totally okay with keeping `com.drfloob.*` and as far as I can tell, a different package name for your shouldn't cause any problems as long as the "main()" activity's package - which is a unique identifier for the app - remains the same.

**Comment by drfloob** [comment]
Try setting the environment variable `ANDROID_SDK` to the path your sdk is in (with no trailing slash). I copied the ant build script from a project generated by `android create project ...`. It's really short, and there's nothing custom about it, so that's my best guess about your build issue. If eclipse can't parse the build script and yet I can, then I >> eclipse. I should be everyone's primary IDE, clearly.

I've fixed a bug or two since you pulled the changes into your dev branch. You may want to freshen up your copy. I think there may be another obvious bug lurking in there, but I haven't had time to dig into it. Also, one negative (but trivial) change I've introduced - if you're redirected to the login screen, and you hit the "back" button, you're in an infinite loop of "could not authenticate". I think that should be handled more gracefully - not sure how yet. Maybe exiting the app & killing the service if the user chooses not to login?

**Comment by poundifdef** [comment]
I've pulled in your latest changes, made a few modifications of my own, and updated the application on the Android Market. Cool beans!

**Pull request closed without merging**
